services:
  linter:
    build:
      context: ..
      dockerfile: lint/Dockerfile
    image: pytest-openapi-lint:latest
    working_dir: /workspace
    volumes:
      - ../:/workspace
    command: ./lint/lint_and_format.sh

